---
name: add_ignore_all_white_spaces
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/111055
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/390657
milestone: '15.9'
type: development
group: group::code review
default_enabled: false
