---
name: add_prepared_state_to_mr
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/109967
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/389249
milestone: '15.9'
type: development
group: group::code review
default_enabled: false
