---
name: admin_jobs_vue
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/98769
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/391194
milestone: '15.9'
type: development
group: group::pipeline execution
default_enabled: false
