---
name: advanced_search_decrease_indexing_timeout
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/111902
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/391570
milestone: '15.9'
type: development
group: group::global search
default_enabled: false
