---
name: arkose_labs_trial_signup_challenge
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/113985
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/395754
milestone: '15.10'
type: development
group: group::anti-abuse
default_enabled: false
