---
name: auto_merge_labels_mr_widget
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/115436
rollout_issue_url:
milestone: '15.11'
type: development
group: group::pipeline execution
default_enabled: false
