---
name: ci_builds_columns_size_validation
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/118148
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/407404
milestone: '16.0'
type: development
group: group::pipeline execution
default_enabled: false
