---
name: ci_include_components
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/109154
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/39064
milestone: '15.9'
type: development
group: group::pipeline authoring
default_enabled: false
