---
name: ci_job_artifact_bulk_destroy
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/110026
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/386768
milestone: '15.10'
type: development
group: group::pipeline security
default_enabled: false
