---
name: ci_limit_environment_scope
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/113171
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/395003
milestone: '15.10'
type: development
group: group::pipeline security
default_enabled: false
