---
name: ci_multi_doc_yaml
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/109137
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/388836
milestone: '15.9'
type: development
group: group::pipeline authoring
default_enabled: true
