name: ci_private_catalog_beta
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/113407
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/394772
milestone: '15.10'
type: development
group: group::pipeline authoring
default_enabled: false

