---
name: ci_remove_legacy_predefined_variables
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/116606
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/404533
milestone: '15.11'
type: development
group: group::pipeline authoring
default_enabled: false
