---
name: data_transfer_monitoring_mock_data
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/113392
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/397693
milestone: '15.11'
type: development
group: group::source code
default_enabled: false
