---
name: disable_runner_graphql_legacy_mode
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/117875
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/344648
milestone: '15.11'
type: development
group: group::runner
default_enabled: false
