---
name: explain_code_chat
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/117674
rollout_issue_url:
milestone: '16.0'
type: development
group: group::source code
default_enabled: false
