---
name: explain_vulnerability
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/117472
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/407282
milestone: '15.11'
type: development
group: group::threat insights
default_enabled: false
