---
name: filter_vulnerability_findings_dismissed_on_default
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/113711
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/396747
milestone: '15.11'
type: development
group: group::threat insights
default_enabled: false
