---
name: hidden_notes
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/112973
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/405148
milestone: '15.11'
type: development
group: group::anti-abuse
default_enabled: false
