---
name: import_details_page
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/116090
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/397650
milestone: '15.11'
type: development
group: group::import
default_enabled: false
