---
name: openai_experimentation
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/116364
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/403855
milestone: '15.11'
type: development
group: group::ai-enablement
default_enabled: false
