---
name: pipeline_name_in_api
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/115310
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/398131
milestone: '15.11'
type: development
group: group::delivery
default_enabled: false
