---
name: pipeline_trigger_merge_status
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/112525
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/392989
milestone: '15.10'
type: development
group: group::code review
default_enabled: false
