---
name: product_analytics_snowplow_support
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/116317
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/403418
milestone: '15.11'
type: development
group: group::product analytics
default_enabled: false
