---
name: product_intelligence_database_event_tracking_batch2
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/116125
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/403041
milestone: '16.0'
type: development
group: group::analytics instrumentation
default_enabled: false
