---
name: prom_metrics_rust
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/119005
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/409023
milestone: '16.0'
type: development
group: group::gitaly::cluster
default_enabled: false
