---
name: restrict_special_characters_in_namespace_path
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/111017
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/390954
milestone: '15.9'
type: development
group: group::tenant scale
default_enabled: false
