---
name: scan_execution_bot_users
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/118089
rollout_issue_url:
milestone: '16.0'
type: development
group: group::security policies
default_enabled: false
