---
name: search_index_integrity
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/112369
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/392981
milestone: '15.10'
type: development
group: group::global search
default_enabled: false
