---
name: sidekiq_execution_application_slis
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/116827
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/407325
milestone: '15.11'
type: development
group: group::scalability
default_enabled: false
