---
name: single_file_file_by_file
introduced_by_url: 'https://gitlab.com/gitlab-org/gitlab/-/merge_requests/111895'
rollout_issue_url: 'https://gitlab.com/gitlab-org/gitlab/-/issues/403571'
milestone: '15.11'
type: development
group: group::code review
default_enabled: false
