---
name: summarize_comments
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/117296
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/406758
milestone: '15.11'
type: development
group: group::ai-enablement
default_enabled: false
