---
name: super_sidebar_peek
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/116914
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/404966
milestone: '15.11'
type: development
group: group::foundations
default_enabled: false
