---
name: use_replica_for_mailers
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/116357
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/408785
milestone: '16.0'
type: development
group: group::scalability
default_enabled: false
