---
name: use_primary_and_secondary_stores_for_db_load_balancing
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/111269
rollout_issue_url:
milestone: '15.9'
type: development
group: group::scalability
default_enabled: false
