---
name: user_spam_scores
introduced_by_url: 'https://gitlab.com/gitlab-org/gitlab/-/merge_requests/118706'
rollout_issue_url: 'https://gitlab.com/gitlab-org/gitlab/-/issues/408753'
milestone: '16.0'
type: development
group: group::antiabuse
default_enabled: false
