---
name: no_code_automation_mvc
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/108692
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/387888
milestone: '15.9'
type: development
group: group::incubation
default_enabled: false
