---
name: package_metadata_synchronization
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/111123
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/390836
milestone: '15.9'
type: development
group: group::composition analysis
default_enabled: true
