---
name: tanuki_bot_parallel
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/117695
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/407555
milestone: '16.0'
type: development
group: group::global search
default_enabled: true
