---
name: use_invoice_preview_api_in_saas_purchase
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/110835
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/390143
milestone: '15.9'
type: development
group: group::purchase
default_enabled: false
