---
name: event_type_filters_deleted
description: Event triggered when audit events streaming event type filters are deleted
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/issues/344848
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/113489
feature_category: audit_events
milestone: '15.10'
saved_to_database: true
streamed: true
