---
name: project_merge_requests_author_approval_updated
description: audit when project mr author approval setting is updated
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/issues/369288
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/106652
milestone: '15.7'
feature_category: projects
saved_to_database: true
streamed: true
