name: project_require_password_to_approve_updated
description: Event triggered on updating project setting for requiring user's password for approval of merge request
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/issues/369280
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/106652
milestone: '15.7'
feature_category: projects
saved_to_database: true
streamed: true
