name: project_printing_merge_request_link_enabled_updated
description: Event triggered on updating setting for projects for enabling printing merge request link
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/issues/369283
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/106652
milestone: '15.7'
feature_category: projects
saved_to_database: true
streamed: true
