name: project_path_updated
description: Event triggered on updating a project's path
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/issues/369271
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/100770
milestone: '15.5'
feature_category: projects
saved_to_database: true
streamed: true
