---
data_category: operational
key_path: counts.commit_comment
description: Count of total unique commit comments. Does not include MR diff comments
product_section: dev
product_stage: create
product_group: source_code
value_type: number
status: active
time_frame: all
data_source: redis
instrumentation_class: RedisMetric
options:
  prefix: note
  event: create_commit
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
performance_indicator_type: []
milestone: "<13.9"
