---
key_path: redis_hll_counters.code_review.i_code_review_merge_request_widget_license_compliance_warning_weekly
description: Count of unique merge requests with license compliance warnings
product_section: dev
product_stage: create
product_group: code_review
value_type: number
status: active
time_frame: 7d
data_source: redis_hll
data_category: optional
introduced_by_url:
milestone: '15.9'
instrumentation_class: RedisHLLMetric
options:
  events:
    - i_code_review_merge_request_widget_license_compliance_warning
distribution:
  - ee
tier:
  - premium
  - ultimate
