---
data_category: operational
key_path: usage_activity_by_stage_monthly.create.action_monthly_active_users_ide_edit
description: Number of unique users per month who edited a file from any web editor
product_section: dev
product_stage: create
product_group: editor
value_type: number
status: active
time_frame: 28d
instrumentation_class: AggregatedMetric
data_source: redis_hll
options:
  aggregate:
    operator: OR
    attribute: user_id
  events:
    - g_edit_by_web_ide
    - g_edit_by_sfe
    - g_edit_by_snippet_ide
    - g_edit_by_live_preview
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
performance_indicator_type:
- gmau
- paid_gmau
milestone: "<13.9"
