---
name: circuit_breaker
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/117993
rollout_issue_url:
milestone: '16.0'
type: ops
group: group::ai-enablement
default_enabled: false
